export enum astrologersAction {
  UPDATE_FILTER = 'UPDATE_FILTER',
  UPDATE_SORTING = 'UPDATE_SORTING',
  DELETE_ASTROLOGER = 'DELETE_ASTROLOGER',
  UPDATE_STATE_FROM_URL = 'UPDATE_STATE_FROM_URL',
}
